class CommandConstants:
    BLOCK_START = "BLOCK START"
    BLOCK_END = "BLOCK END"
    COMMAND_VAR = "__COMMAND__"
    IGNORE_VARIABLE_REPLACEMENT = "IGNORE_VARIABLE_REPLACEMENT"
    TEMPLATE_PREFIX = "$"
